# Generated by Django 5.0.3 on 2024-07-15 08:26

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_description',
            field=models.TextField(default='none'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_location',
            field=models.TextField(default='none'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
